import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { PostModal } from './ui/home/post/[id]/post-modal';
import { CreatePostModal } from './ui/home/create-post-modal';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='bg-base-200'>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
